AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy K8mgr Instances
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
  #------------------
  InstanceType:
    Description: (Optional) Instance type
    Type: String
    Default: t3.large
  AmiId:
    Description: (Optional) AMI ID
    Type: String
    Default: ami-00d101850e971728d
  KeyName:
    Description: (required) Name of an existing EC2 key pair
    Type: "AWS::EC2::KeyPair::KeyName"
  AutoRecoveryMinutes:
    Description: (optional) Auto Recovery Time(Minutes)
    Type: Number
    Default: 1
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Environment
        Parameters: 
          - Environment
      -
        Label:
          default:  Instances
        Parameters:
          - InstanceType
          - AmiId
          - KeyName
          - AutoRecoveryMinutes
#----------------------------------------------
Conditions: 
  CheckAutoRecovery: !Not [!Equals [!Ref AutoRecoveryMinutes, 0 ]]
#----------------------------------------------
Resources:
  #------------------ DockerDev:
  Client:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub ${AmiId}
      InstanceType: !Sub ${InstanceType}
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${Environment}-Iam-ClientInstanceProfile
      Monitoring: yes
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId:
            Fn::ImportValue: !Sub ${Environment}-VpcFunc-PublicSubnet1Id
          GroupSet:
            - Fn::ImportValue: !Sub ${Environment}-Sg-ClientSGId
          #AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Client
  AutoRecovery:
    Type: AWS::CloudWatch::Alarm
    Condition: CheckAutoRecovery
    Properties:
      AlarmDescription: AutoRecovery for the Client
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: !Ref AutoRecoveryMinutes
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
      - !Sub "arn:aws:automate:${AWS::Region}:ec2:recover"
      - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:admin"
      Dimensions:
      - Name: InstanceId
        Value: !Ref Client
    DependsOn: Client
  LocalDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcInternalDnsName
      Comment: A record for the private IP address of the Client.
      Name:
        Fn::Join:
          - ""
          - - "client."
            - Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcInternalDnsName
      Type: A
      TTL: 60
      ResourceRecords:
        - !GetAtt Client.PrivateIp
Outputs:
  #---------------- EC2 Instance
  ClientId:
    Description: Client Instance ID
    Value: !Ref Client
    Export:
      Name: !Sub ${AWS::StackName}-ClientId
  ClientPrivateIP:
    Description: Bastion Instance Private IP
    Value: !GetAtt Client.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-ClientPrivateIP