AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy K8mgr Instances
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
  #------------------
  InstanceType:
    Description: (Optional) Instance type
    Type: String
    Default: t3.large
  AmiId:
    Description: (Optional) AMI ID
    Type: String
    Default: ami-0ff21806645c5e492
  KeyName:
    Description: (required) Name of an existing EC2 key pair
    Type: "AWS::EC2::KeyPair::KeyName"
  AutoRecoveryMinutes:
    Description: (optional) Auto Recovery Time(Minutes)
    Type: Number
    Default: 1
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Environment
        Parameters: 
          - Environment
      -
        Label:
          default:  Instances
        Parameters:
          - InstanceType
          - AmiId
          - KeyName
          - AutoRecoveryMinutes
#----------------------------------------------
Conditions: 
  CheckAutoRecovery: !Not [!Equals [!Ref AutoRecoveryMinutes, 0 ]]
#----------------------------------------------
Resources:
  #------------------ DockerDev:
  Manager:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub ${AmiId}
      InstanceType: !Sub ${InstanceType}
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${Environment}-Iam-ManagerInstanceRolePlofile
      Monitoring: yes
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId:
            Fn::ImportValue: !Sub ${Environment}-VpcFunc-PublicSubnet2Id
          GroupSet:
            - Fn::ImportValue: !Sub ${Environment}-Sg-ManagerSGId
          #AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Manager
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum -y update
          hostnamectl set-hostname "${Environment}-Manager"

          # Setup AWS CLI
          aws configure set region ${AWS::Region}
          aws configure set output json

  AutoRecovery:
    Type: AWS::CloudWatch::Alarm
    Condition: CheckAutoRecovery
    Properties:
      AlarmDescription: AutoRecovery for the Manager
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: !Ref AutoRecoveryMinutes
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
      - !Sub "arn:aws:automate:${AWS::Region}:ec2:recover"
      - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:admin"
      Dimensions:
      - Name: InstanceId
        Value: !Ref Manager
    DependsOn: Manager
  LocalDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcInternalDnsName
      Comment: A record for the private IP address of the Manager.
      Name:
        Fn::Join:
          - ""
          - - "Manager."
            - Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcInternalDnsName
      Type: A
      TTL: 60
      ResourceRecords:
        - !GetAtt Manager.PrivateIp
Outputs:
  #---------------- EC2 Instance
  ManagerId:
    Description: Manager Instance ID
    Value: !Ref Manager
    Export:
      Name: !Sub ${AWS::StackName}-ManagerId
  ManagerPrivateIP:
    Description: Bastion Instance Private IP
    Value: !GetAtt Manager.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-ManagerPrivateIP