AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy IAM Role for Instances
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
Resources:
  # EC2インスタンスに付与するインスタンスロールの作成を行う
  # ここでは、マネージドポリシーのみ付与し、
  # S3などリソースを意識するポリシーは各リソースデプロイ時にアタッチする
  #---IAM Role(For Instances)
  ClientInstanceRole:
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  ClientInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${Environment}-ClientInstanceProfile-${AWS::StackName}
      Path: "/"
      Roles:
        - !Ref ClientInstanceRole
  #---
  StorageGatewayRole:
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  StorageGatewayPlofile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${Environment}-StorageGatewayRole-${AWS::StackName}
      Path: "/"
      Roles:
        - !Ref StorageGatewayRole
  #---
  StorageGatewayBucketAccessRole:
    Type: AWS::IAM::Role
    Properties: 
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - storagegateway.amazonaws.com
            Action:
              - sts:AssumeRole
  #---
  ManagerInstanceRole:
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AdministratorAccess
  ManagerInstanceRolePlofile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${Environment}-ManagerInstanceRole-${AWS::StackName}
      Path: "/"
      Roles:
        - !Ref ManagerInstanceRole
Outputs:
  #---------------- IAM Role
  ClientInstanceRoleArn:
    Description: Role Arn of ClientInstanceRole
    Value: !GetAtt ClientInstanceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ClientInstanceRoleArn
  ClientInstanceRoleName:
    Description: Role Name of ClientInstanceRole
    Value: !Ref ClientInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-ClientInstanceRoleName
  ClientInstanceProfile:
    Description: Arn of ClientInstance Profile
    Value: !Ref ClientInstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-ClientInstanceProfile
  #------------------
  StorageGatewayRoleArn:
    Description: Role Arn of StorageGatewayRole
    Value: !GetAtt StorageGatewayRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StorageGatewayRoleArn
  StorageGatewayRoleName:
    Description: Role Name of StorageGatewayRole
    Value: !Ref StorageGatewayRole
    Export:
      Name: !Sub ${AWS::StackName}-StorageGatewayRoleName
  StorageGatewayPlofile:
    Description: Arn of StorageGatewayPlofile
    Value: !Ref StorageGatewayPlofile
    Export:
      Name: !Sub ${AWS::StackName}-StorageGatewayPlofile
  #------------------
  StorageGatewayBucketAccessRoleArn:
    Description: Role Arn of StorageGatewayBucketAccessRole
    Value: !GetAtt StorageGatewayBucketAccessRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StorageGatewayBucketAccessRoleArn
  StorageGatewayBucketAccessRoleName:
    Description: Role Name of StorageGatewayBucketAccessRole
    Value: !Ref StorageGatewayBucketAccessRole
    Export:
      Name: !Sub ${AWS::StackName}-StorageGatewayBucketAccessRoleName
  #------------------
  ManagerInstanceRoleArn:
    Description: Role Arn of ManagerInstanceRole
    Value: !GetAtt ManagerInstanceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ManagerInstanceRoleArn
  ManagerInstanceRoleName:
    Description: Role Name of ManagerInstanceRole
    Value: !Ref ManagerInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-ManagerInstanceRoleName
  ManagerInstanceRolePlofile:
    Description: Arn of ManagerInstanceRolePlofile
    Value: !Ref ManagerInstanceRolePlofile
    Export:
      Name: !Sub ${AWS::StackName}-ManagerInstanceRolePlofile



