AWSTemplateFormatVersion: '2010-09-09'
Description: Application VPC peering commonVPC between operationVPC
#----------------------------------------------
Parameters:
  Environment:
    Type: String
    AllowedPattern: "[a-zA-Z0-9=-@+?[?]?<?>._]*"
    ConstraintDescription: Can contain only ASCII characters.
    Description: (required) Environment name
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: Environment
        Parameters: 
          - Environment
#----------------------------------------------
Resources:
  #------------------ VPC Peering
  VpcPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcId
      PeerVpcId: 
        Fn::ImportValue: !Sub ${Environment}-VpcExter-VpcId
      Tags:
        - Key: Name
          Value: VPCPeer-Function2External
        - Key: Environment
          Value: !Ref Environment
  #------------------ Add routings
  #--- FunctionVPC
  AddRouteDestExternalVpcToFunctionRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-PublicSubnetRouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-VpcExter-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteDestExternalVpcToFunctionPrivate1RouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-PrivateSubnet1RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-VpcExter-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
  AddRouteDestExternalVpcToFunctionPrivate2RouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-PrivateSubnet2RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-VpcExter-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering

  #--- ExternalVPC
  AddRouteDestFunctionVpcToFExternalPublicRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub ${Environment}-VpcExter-RouteTableId
      DestinationCidrBlock:
        Fn::ImportValue: !Sub ${Environment}-VpcFunc-VpcCidr
      VpcPeeringConnectionId: !Ref VpcPeering
